[build]
builder = "nixpacks"

[deploy]
startCommand = "php bin/console cache:clear --no-warmup && php bin/console cache:warmup && php bin/console asset-map:compile && php bin/console doctrine:migrations:migrate --no-interaction && php -S 0.0.0.0:$PORT -t public/"
healthcheckPath = "/"
healthcheckTimeout = 100
